spring.datasource.url=jdbc:postgresql://localhost:5433/simulacrum
spring.datasource.username=simulacrum
spring.datasource.password=simulacrum
spring.flyway.enabled=true
spring.flyway.schemas=simulacrum
spring.flyway.locations=classpath:db/migration
